language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.1
before_script:
- node server &
- npm install gulp bower mocha-phantomjs -g
- bower install
- gulp mx
- phantomjs --version
script:
- npm run-script browser-test
- npm run-script browser-test-build
- npm run-script browser-test-cover